### PR TITLE
Seperate the web server and subscriber to two different classes

### PR DESCRIPTION
**Pull request by skrzepto**
Purpose: cleaning up the code

*note: Can't really test FeedQueue with unittests*

----

Unit tests results
```
collected 14 items

tests/test_sse_subscriber.py .........
tests/test_sse_webserver.py .....
---------- coverage: platform linux2, python 2.7.12-final-0 ----------
Name                       Stmts   Miss  Cover
----------------------------------------------
fmn/__init__.py                0      0   100%
fmn/sse/FeedQueue.py          37     30    19%
fmn/sse/__init__.py            0      0   100%
fmn/sse/sse_webserver.py      54      8    85%
fmn/sse/subscriber.py         73     12    84%

----------------------------------------------
TOTAL                        164     50    70%
```

### CODE REVIEW

**Comment by skrzepto** [comment]
issue #20

**Comment by skrzepto** [comment]
Odd in F24 runs fine but in centos 7 it complains

```
(fmn)[root@centos-512mb-nyc1-01 fmn.sse]# PYTHONPATH=. python fmn/sse/sse_webserver.py 
WARNING:fedmsg.crypto.x509:Crypto disabled ImportError('No module named M2Crypto',)
Traceback (most recent call last):
  File "fmn/sse/sse_webserver.py", line 8, in <module>
    from fmn.sse.subscriber import SSESubscriber
ImportError: No module named subscriber
```

**Comment by skrzepto** [comment]
works fine on Centos 7 and F24.

**Comment by skrzepto** [comment]
updated readme to fix #23

**Comment by skrzepto** [comment]
still running fine since noon today.

**Comment by pypingou** [comment]
Looks alright to me :)

**Pull request merged**
