### PR TITLE
Readme fix

### PR DESCRIPTION
**Pull request by skrzepto**
* fixing readme and adjusting it to use pip install -r instead of setup install to not have issues when developing

* adding fedmsg a missing dep

* removing twisted version from requirements file since new version close after 1-2 messages after actually being closed and then gets removed from the datastructure

* fixing typo in readme

### CODE REVIEW

**Comment by skrzepto** [comment]
maybe we should rethink adding fedmsg as a dep. It's needed now for the config. But I can use `configparser` instead. Thoughts?

**Comment by pypingou** [comment]
Moving to ``configparser`` is a good idea but I think outside the scope of this PR, so :+1: to merge as is :)

**Comment by pypingou** [comment]
I left a couple of (minor) comments on #34, since I don't know how busy you are, I hope you won't mind that I merge this PR directly :)

**Comment by skrzepto** [comment]
No worries :) I've been a little busy these past few weeks and upcoming weeks dont look any better :/

**Pull request merged**
